### ISSUE TITLE
Is this still valid? If not, how do I configure stateful modules?

### ISSUE THREAD

**Issue by tomitrescak** [basarat/fuse-hmr#1]
Hi, it looks like HMR now works out of the box without fusebox-hmr. Yet, how do I configure stateful modules? I guess the only way is with fusebox-hmr no?

**Comment by tomitrescak** [comment]
import {setStatefulModules} from 'fuse-box/modules/fuse-hmr';

setStatefulModules(name => {
  // Add the things you think are stateful:
  return /router/.test(name) || /state/.test(name);
});

**Comment by basarat** [comment]
Indeed. I should update the readme as this package is no longer needed :rose:

**Comment by basarat** [comment]
Added to readme https://github.com/basarat/fuse-hmr/blob/master/README.md#warning :rose:
